### ISSUE TITLE
Missing cursesw.h?

### ISSUE THREAD

**Issue by hinesro** [jmoon018/PacVim#2]
A lot of the cpp files are linking to this header file, but it's not in the src directory. Could it have been removed by accident?

**Comment by alexbowers** [comment]
Same issue

**Comment by RossBarnie** [comment]
Same issue

**Comment by jmoon018** [comment]
It was not accidental. Curses is a graphics library for terminals, and I used it to speed up the development process of the game. PacVim, therefore, require Curses to be downloaded and installed in order to work. After proper installation of Curses, the '#include <cursesw.h>' should register and the game will compile. I will add this to the README for the future.

I have only tested this on Ubuntu. It can be installed on Ubuntu via the terminal: 
<code>sudo apt-get install libncurses5-dev </code>

I have not tried it, but <a href="http://geeksww.com/tutorials/operating_systems/linux/tools/how_to_download_compile_and_install_gnu_ncurses_on_debianubuntu_linux.php"tutorial>this</a> should provide good instructions for downloading, configuring, and installing

<a href="http://ftp.gnu.org/pub/gnu/ncurses/">This page</a> also contains the download links for ncurses

Let me know if this fixes your issues

**Comment by hinesro** [comment]
Thanks, that solved it! Great program.

**Comment by betamos** [comment]
Is that ncurses version really necessary, or could the old header files be used instead? I am asking because we don't really have access to it in homebrew for OS X yet, and probably other package managers as well, since it's a development build.

**Comment by vadikace** [comment]
I have installed ncurses like mentioned in this gist https://gist.github.com/cnruby/960344 but still have an issue that cursesw.h missing.
```
In file included from src/ghost1.cpp:1:
In file included from src/ghost1.h:4:
In file included from src/avatar.h:8:
In file included from src/helperFns.h:4:
src/globals.h:6:10: fatal error: 'cursesw.h' file not found
#include <cursesw.h>
         ^
1 error generated.
make: *** [all] Error 1```

**Comment by MatthewWest** [comment]
Just commenting on here, I've submitted a pull request that fixes the ncurses and other issues for Mac. With homebrew, you'll have to manually `brew install ncurses` then `brew link ncurses --force` because it refuses to link it by default otherwise. If you want my fork, you can use [my fork](https://github.com/MatthewWest/PacVim) until it gets merged into the main repo.

**Comment by jmoon018** [comment]
I have merged @MatthewWest 's code into the main repo. I did a little bit of testing for OS X and it worked for me -- if there are still any installation problems, make a new issue w/ your operating system

Thanks
