### ISSUE TITLE
Colour scheme

### ISSUE THREAD

**Issue by Haakenlid** [jmoon018/PacVim#6]
Distinguishing green from red is hard for colourblind people. Is there any way to change the colour scheme inside the game?

**Comment by jmoon018** [comment]
@Haakenlid 
Yes.

You may either adjust which of the default colors you want to use, or you can create your own colors (which is a bit more of a pain)

In `game.cpp`, there is a method called `void defineColors() {`
There are a list of commands that initialize the colors, EG: `init_pair(1, COLOR_RED, COLOR_BLACK)`
Unfortunately, there are only 8 default colors (COLOR_RED, COLOR_GREEN, COLOR_YELLOW, COLOR_BLUE, COLOR_MAGENTA, COLOR_CYAN, COLOR_WHITE, COLOR_BLACK).
If the red Ghosts are difficult for you to see, you can, for example, <b>change the line</b> `init_pair(1, COLOR_RED, COLOR_BLACK);` to `init_pair(1, COLOR_BLUE, COLOR_BLACK);`
The last parameter in `init_pair` is the background color, so you could also do `init_pair(1, COLOR_BLUE, COLOR_BLUE);` and the Ghosts would be a solid blue

If you want to make your own colors, then you'd have to make sure your xterm version is xterm-256color. I believe typing `export TERM=xterm-256color` in the terminal should change this. However, the change is not permanent. Then, in `void defineColors()`, immediately after `start_colors();`, write something such as `init_color(COLOR_RED, 100, 1000, 1000);` This will change the COLOR_RED to the RGB values specified after that (the max RGB value is 1000 instead of the usual 255)

let me know if that does / does not help

**Comment by Haakenlid** [comment]
Thanks. I got that to work. The main problem was visited text, ghosts and unvisited text are not different enough. This is the colour scheme that I found works best for me. Using a red background color for monsters and traps is useful.

    init_pair(1, COLOR_YELLOW, COLOR_RED);
    init_pair(2, COLOR_YELLOW, COLOR_BLACK);
    init_pair(3, COLOR_YELLOW, COLOR_BLACK);
    init_pair(4, COLOR_BLUE, COLOR_BLACK);
    init_pair(5, COLOR_MAGENTA, COLOR_BLACK);
    init_pair(6, COLOR_BLACK, COLOR_RED);
    init_pair(7, COLOR_WHITE, COLOR_BLACK);

**Comment by jmoon018** [comment]
Awesome, glad you got it to work. That will definitely help the other red-green color blind people too, so thanks!

Closing becasue this issue has been resolved
